# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: /blog/:year/:month/:day/:title.html
relative_permalinks: true


# Setup
title:               Arjun Sajeev
tagline:             'Blog'
description:         'Web Developer.Computer Science Student'
url:                 http://arjunsajeev.github.io
baseurl:             ''
paginate:            5
gems:
  - jekyll-sitemap

# About/contact
author:
  name:              Arjun Sajeev
  url:               https://twitter.com/arjunsajeev04
  email:             arjunsajeev04@gmail.com

# Custom vars
version:             1.0.0
