# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Arjun Sajeev
tagline:             '-->blog'
description:         'My development blog'
url:                 http://lanyon.getpoole.com
baseurl:             'arjunsajeev.github.io'
paginate:            5

# About/contact
author:
  name:              Arjun Sajeev
  url:               https://twitter.com/arjunsajeev04
  email:             arjunsajeev04@gmail.com

# Custom vars
version:             1.0.0
